# SPDX-FileCopyrightText: 2025 Reo Yamaguchi
# SPDX-License-Identifier: BSD-3-Clause:
name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          apt-get update
          apt-get install -y python3-psutil bc rsync
          
          mkdir -p /root/ros2_ws/src/my_cpu_monitor
          rsync -av ./ /root/ros2_ws/src/my_cpu_monitor/
          
          cd /root/ros2_ws
          bash -c "source /opt/ros/humble/setup.bash && colcon build"
          
          chmod +x ./src/my_cpu_monitor/test/test.bash
          bash -xv ./src/my_cpu_monitor/test/test.bash